openapi: 3.0.1
info:
  title: Prices API
  description: >-
    Price API que permite realizar la busqueda mediante fecha de aplicación,
    identificador de producto, identificador de cadena.
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Demo
    email: api@app.com
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: 1.0.0
servers:
  - url: http://localhost:8443
    description: Generated server url
paths:
  /ms-prices/api/v1/prices/search:
    get:
      tags:
        - prices-controller
      operationId: searchByStartDate
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
        - name: productId
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '405':
          description: M
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    ApiError:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetail'

    ApiErrorDetail:
      type: object
      properties:
        messages:
          type: string
        uri:
          type: string